export const PLAN_LIMITS = {
  free: {
    'monitoring.services.max': 1,
    'teams.max': 1,
    'members.max': 3,
    'statusPages.max': 1,
    'apiKeys.max': 1,
    'webhooks.max': 1,
    'incidents.max': 5,
    'postmortems.max': 1,
    'escalationPolicies.max': 1,
    'onCallSchedules.max': 1,
    'maintenance.max': 1,
    'healthChecks.max': 100,
    'auditEvents.max': 25,
    'checkInterval.min': 60,
  },
  pro: {
    'monitoring.services.max': 25,
    'teams.max': 10,
    'members.max': 50,
    'statusPages.max': 5,
    'apiKeys.max': 10,
    'webhooks.max': 10,
    'incidents.max': 500,
    'postmortems.max': 100,
    'escalationPolicies.max': 25,
    'onCallSchedules.max': 25,
    'maintenance.max': 50,
    'healthChecks.max': 20000,
    'auditEvents.max': 2000,
    'checkInterval.min': 15,
  },
  business: {
    'monitoring.services.max': 100,
    'teams.max': 25,
    'members.max': 200,
    'statusPages.max': 20,
    'apiKeys.max': 25,
    'webhooks.max': 25,
    'incidents.max': 5000,
    'postmortems.max': 1000,
    'escalationPolicies.max': 100,
    'onCallSchedules.max': 100,
    'maintenance.max': 200,
    'healthChecks.max': 100000,
    'auditEvents.max': 10000,
    'checkInterval.min': 15,
  },
};

export function limitFor(plan, key) {
  const limits = PLAN_LIMITS[plan] || PLAN_LIMITS.free;
  return limits[key];
}
