export const ROLES = ['owner', 'admin', 'incident_manager', 'engineer', 'viewer'];

const ROLE_PERMISSIONS = {
  owner: [
    'org:read',
    'org:update',
    'member:read',
    'member:manage',
    'team:read',
    'team:write',
    'service:read',
    'service:write',
    'incident:read',
    'incident:create',
    'incident:update',
    'incident:transition',
    'incident:resolve',
    'incident:comment',
    'notification:read',
    'oncall:read',
    'oncall:write',
    'escalation:read',
    'escalation:write',
    'postmortem:read',
    'postmortem:write',
    'status:read',
    'status:write',
  ],
  admin: [
    'org:read',
    'member:read',
    'member:manage',
    'team:read',
    'team:write',
    'service:read',
    'service:write',
    'incident:read',
    'incident:create',
    'incident:update',
    'incident:transition',
    'incident:resolve',
    'incident:comment',
    'notification:read',
    'oncall:read',
    'oncall:write',
    'escalation:read',
    'escalation:write',
    'postmortem:read',
    'postmortem:write',
    'status:read',
    'status:write',
  ],
  incident_manager: [
    'org:read',
    'member:read',
    'team:read',
    'service:read',
    'incident:read',
    'incident:create',
    'incident:update',
    'incident:transition',
    'incident:resolve',
    'incident:comment',
    'notification:read',
    'oncall:read',
    'escalation:read',
    'postmortem:read',
    'postmortem:write',
    'status:read',
    'status:write',
  ],
  engineer: [
    'org:read',
    'member:read',
    'team:read',
    'service:read',
    'incident:read',
    'incident:update',
    'incident:transition',
    'incident:resolve',
    'incident:comment',
    'notification:read',
    'oncall:read',
    'escalation:read',
    'postmortem:read',
    'postmortem:write',
    'status:read',
    'status:write',
  ],
  viewer: [
    'org:read',
    'member:read',
    'team:read',
    'service:read',
    'incident:read',
    'notification:read',
    'oncall:read',
    'escalation:read',
    'postmortem:read',
    'status:read',
  ],
};

export function permissionsFor(role) {
  return ROLE_PERMISSIONS[role] ? [...ROLE_PERMISSIONS[role]] : [];
}

export function hasPermission(role, permission) {
  return permissionsFor(role).includes(permission);
}
